<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // Table Products
        DB::table('products')->insert([
            [
                'manu_id' => '1',
                'product_name' => 'Điện thoại iPhone 11 64GB',
                'price' => '14990000',
                'image' => 'iphone-11-vang-1-2-org.jpg',
                'description' => 'Màn hình: IPS LCD6.1"Liquid Retina#Hệ điều hành: iOS 15#Camera sau: 2 camera 12 MP#Camera trước: 12 MP#Chip: Apple A13 Bionic#RAM: 4 GB Bộ nhớ trong: 64 GB#SIM: 1 Nano SIM & 1 eSIMHỗ trợ 4G Pin, Sạc: 3110 mAh18 W',
                'quantity' => '5',
                'feature' => '1',
                'sale' => '5',
                'star' => '5',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '1',
                'product_name' => 'Điện thoại iPhone 13 mini 128GB',
                'price' => '21990000',
                'image' => 'iphone-13-mini-hong-1.jpg',
                'description' => 'Màn hình: OLED5.4"Super Retina XDR#Hệ điều hành:iOS 15#Camera sau: 2 camera 12 MP#Camera trước: 12 MP#Chip: Apple A15 Bionic#RAM: 4 GBBộ nhớ trong: 128 GB#SIM: 1 Nano SIM & 1 eSIMHỗ trợ 5G#Pin, Sạc: 2438 mAh20 W',
                'quantity' => '5',
                'feature' => '1',
                'sale' => '12',
                'star' => '4',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '1',
                'product_name' => 'iPhone SE (2022)',
                'price' => '11990000',
                'image' => 'iphone-se-white-600x600.jpg',
                'description' => 'Màn hình 4.7", Chip Apple A15 Bionic#RAM 3 GB, ROM 64 GB#Camera sau: 12 MP#Camera trước: 7 MP#Pin 2018 mAh, Sạc 20 W',
                'quantity' => '10',
                'feature' => '1',
                'sale' => '5',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '1',
                'product_name' => 'iPhone 13 mini',
                'price' => '19290000',
                'image' => 'iphone-13-mini-midnight-1-600x600.jpg',
                'description' => 'Màn hình 5.4", Chip Apple A15 Bionic#RAM 4 GB, ROM 128 GB#Camera sau: 2 camera 12 MP#Camera trước: 12 MP#Pin 2438 mAh, Sạc 20 W',
                'quantity' => '5',
                'feature' => '1',
                'sale' => '5',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '1',
                'product_name' => 'iPhone 12 mini',
                'price' => '18990000',
                'image' => 'iphone-12-mini-den-15-600x600.jpg',
                'description' => 'Màn hình 5.4", Chip Apple A14 Bionic#RAM 4 GB, ROM 64 GB#Camera sau: 2 camera 12 MP#Camera trước: 12 MP#Pin 2227 mAh, Sạc 20 W',
                'quantity' => '6',
                'feature' => '1',
                'sale' => '5',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '1',
                'product_name' => 'iPhone 12 ',
                'price' => '19190000',
                'image' => 'iphone-12-xanh-la-new-2-600x600.jpg',
                'description' => 'Màn hình 6.1", Chip Apple A14 Bionic#RAM 4 GB, ROM 64 GB#Camera sau: 2 camera 12 MP#Camera trước: 12 MP#Pin 2815 mAh, Sạc 20 W',
                'quantity' => '7',
                'feature' => '1',
                'sale' => '6',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '1',
                'product_name' => 'iPhone 13',
                'price' => '22790000',
                'image' => 'iphone-13.jpg',
                'description' => 'Màn hình: OLED6.1"Super Retina XDR#Hệ điều hành: iOS 15#Camera sau: 3 camera 12 MP#Camera trước: 12 MP#Chip: Apple A15 Bionic#RAM: 6 GB#Bộ nhớ trong: 128 GB#SIM:1 Nano SIM & 1 eSIM Hỗ trợ 5G#Pin, Sạc: 3240 mAh, 20 W',
                'quantity' => '10',
                'feature' => '1',
                'sale' => '3',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '1',
                'product_name' => 'iPhone 12 Pro Max',
                'price' => '29990000',
                'image' => 'iphone-12promax.jpg',
                'description' => 'Màn hình: OLED6.7"Super Retina XDR#Hệ điều hành: iOS 15#Camera sau: 3 camera 12 MP#Camera trước: 12 MP#Chip: Apple A14 Bionic#RAM: 6 GB#Bộ nhớ trong: 256 GB#SIM:1 Nano SIM & 1 eSIM Hỗ trợ 5G#Pin, Sạc: 3687 mAh, 20 W',
                'quantity' => '15',
                'feature' => '1',
                'sale' => '10',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '1',
                'product_name' => 'iPhone 12 Pro',
                'price' => '26290000',
                'image' => 'iphone-12pro.jpg',
                'description' => 'Màn hình: OLED6.1"Super Retina XDR#Hệ điều hành: iOS 15#Camera sau: 3 camera 12 MP#Camera trước: 12 MP#Chip: Apple A14 Bionic#RAM: 6 GB#Bộ nhớ trong: 256 GB#SIM:1 Nano SIM & 1 eSIM Hỗ trợ 5G#Pin, Sạc: 2815 mAh, 20 W',
                'quantity' => '20',
                'feature' => '1',
                'sale' => '15',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            //Laptop
            [
                'manu_id' => '5',
                'product_name' => 'Laptop Apple MacBook Air M1 2020 16GB/256GB/7-core GPU',
                'price' => '28990000',
                'image' => 'macbook-air-m1-2020-gray-600x600.jpg',
                'description' => 'CPU:Apple M1#RAM: 16 GB#Ổ cứng: 256 GB SSD#Màn hình: 13.3"Retina (2560 x 1600)#Card màn hình: Card tích hợp7 nhân GPU#Cổng kết nối: 2 x Thunderbolt 3 (USB-C)Jack tai nghe 3.5 mm#Đặc biệt: Có đèn bàn phím#Hệ điều hành: Mac OS#Thiết kế: Vỏ kim loại nguyên khối#Kích thước, trọng lượng: Dài 304.1 mm - Rộng 212.4 mm - Dày 4.1 mm đến 16.1 mm - Nặng 1.29 kg#Thời điểm ra mắt: 2020',
                'quantity' => '5',
                'feature' => '1',
                'sale' => '1',
                'star' => '4',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '5',
                'product_name' => 'Laptop Apple MacBook Pro M1 2020/16GB/256GB',
                'price' => '34990000',
                'image' => 'macbook-pro-m1-2020-gray-600x600.jpg',
                'description' => 'CPU: Apple M1#RAM: 16 GB#Ổ cứng: 256 GB SSD#Màn hình: 13.3"Retina (2560 x 1600)#Card màn hình: Card tích hợp8 nhân GPU#Cổng kết nối: 2 x Thunderbolt 3 (USB-C)Jack tai nghe 3.5 mm#Đặc biệt: Có đèn bàn phím#Hệ điều hành: Mac OS#Thiết kế: Vỏ kim loại nguyên khối#Kích thước, trọng lượng: Dài 304.1 mm - Rộng 212.4 mm - Dày 15.6 mm - Nặng 1.4 kg#Thời điểm ra mắt: 2020',
                'quantity' => '5',
                'feature' => '1',
                'sale' => '2',
                'star' => '4',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '5',
                'product_name' => 'Laptop MacBook Pro 14 M1 Max 2021 10-core CPU/32GB/512GB/24-core GPU',
                'price' => '73400000',
                'image' => 'macbook-pro-14-m1-max-2021-10-core-cpu-600x600.jpg',
                'description' => 'CPU: Apple M1 Max400GB/s memory bandwidth#RAM: 32 GB#Ổ cứng: 512 GB SSD#Màn hình: 14.2 inchLiquid Retina XDR display (3024 x 1964)120Hz#Card màn hình: Card tích hợp24 nhân GPU#Cổng kết nối: 3 x Thunderbolt 4 USB-CHDMIJack tai nghe 3.5 mm#Đặc biệt: Có đèn bàn phím#Hệ điều hành: Mac OS#Thiết kế: Vỏ kim loại nguyên khối#Kích thước, trọng lượng: Dài 312.6 mm - Rộng 221.2 mm - Dày 15.5 mm - Nặng 1.6 kg#Thời điểm ra mắt: 10/2021 ',
                'quantity' => '5',
                'feature' => '1',
                'sale' => '7',
                'star' => '4',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '5',
                'product_name' => 'Laptop MacBook Pro 14 M1 Pro 2021 10-core CPU/32GB/512GB/16-core GPU',
                'price' => '68490000',
                'image' => 'macbook-pro-14-inch-m1-pro-2021-10-core-cpu-thumb-1-600x600.jpg',
                'description' => 'CPU: Apple M1 Pro200GB/s memory bandwidth#RAM: 32 GB#Ổ cứng: 512 GB SSD#Màn hình: 14.2 inchLiquid Retina XDR display (3024 x 1964)120Hz#Card màn hình: Card tích hợp16 core-GPU#Cổng kết nối: 3 x Thunderbolt 4 USB-CHDMIJack tai nghe 3.5 mm#Đặc biệt: Có đèn bàn phím#Hệ điều hành: Mac OS#Thiết kế: Vỏ kim loại nguyên khối#Kích thước, trọng lượng: Dài 312.6 mm - Rộng 221.2 mm - Dày 15.5 mm - Nặng 1.6 kg#Thời điểm ra mắt: 10/2021',
                'quantity' => '5',
                'feature' => '1',
                'sale' => '12',
                'star' => '4',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '5',
                'product_name' => 'Laptop MacBook Pro 14 M1 Pro 2021 8-core CPU/32GB/512GB/14-core GPU',
                'price' => '61490000',
                'image' => 'macbook-pro-14-inch-m1-pro-2021-8-core-cpu-thumb-1-600x600.jpg',
                'description' => 'CPU: Apple M1 Pro200GB/s memory bandwidth#RAM: 32 GB#Ổ cứng: 512 GB SSD#Màn hình: 14.2 inchLiquid Retina XDR display (3024 x 1964)120Hz#Card màn hình: Card tích hợp14 core-GPU#Cổng kết nối: 3 x Thunderbolt 4 USB-CHDMIJack tai nghe 3.5 mm#Đặc biệt: Có đèn bàn phím#Hệ điều hành: Mac OS#Thiết kế: Vỏ kim loại nguyên khối#Kích thước, trọng lượng: Dài 312.6 mm - Rộng 221.2 mm - Dày 15.5 mm - Nặng 1.6 kg#Thời điểm ra mắt: 10/2021',
                'quantity' => '5',
                'feature' => '1',
                'sale' => '12',
                'star' => '4',
                'created_at' => '2022-05-26',
            ],
            //Tai nghe
            [
                'manu_id' => '4',
                'product_name' => 'Tai nghe Bluetooth AirPods 2 Wireless charge Apple MRXJ2',
                'price' => '3490000',
                'image' => 'tai-nghe-bluetooth-airpods-2-wireless-charge-mrxj2-thumb-600x600.jpg',
                'description' => 'Thời gian tai nghe: Dùng 5 giờ - Sạc 2 giờ#Thời gian hộp sạc: Dùng 24 giờ - Sạc 3 giờ#Cổng sạc: LightningSạc không dây#Công nghệ âm thanh: Chip Apple H1#Tương thích: AndroidiOS (iPhone)#Tiện ích: Có mic thoại#Hỗ trợ kết nối: Bluetooth 5.0#Điều khiển bằng: Cảm ứng chạm Hãng Apple.',
                'quantity' => '10',
                'feature' => '1',
                'sale' => '15',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '4',
                'product_name' => 'Tai nghe Bluetooth AirPods Pro MagSafe Charge Apple MLWK3 Trắng',
                'price' => '5190000',
                'image' => 'bluetooth-airpods-pro-magsafe-charge-apple-mlwk3-thumb-600x600.jpg',
                'description' => 'Pin: Dùng 5 giờ - Sạc 2 giờ#Cổng sạc: LightningSạc không dâySạc MagSafe#Công nghệ âm thanh: Active Noise CancellationAdaptive EQCustom high-excursion Apple driverHigh Dynamic RangeSpatial AudioTransparency Mode#Tương thích: AndroidiOS (iPhone)iPadOS (iPad)MacOS (Macbook, iMac)#Tiện ích: Chống nước IPX4Chống ồnCó mic thoại#Hỗ trợ kết nối: Bluetooth 5.0#Điều khiển bằng: Cảm ứng chạm Hãng Apple',
                'quantity' => '10',
                'feature' => '1',
                'sale' => '15',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '4',
                'product_name' => 'Tai nghe Bluetooth AirPods 3 Apple MME73 Trắng ',
                'price' => '4490000',
                'image' => 'airpods-3-hop-sac-khong-day-thumb-600x600.jpg',
                'description' => 'Pin: Dùng 6 giờ - Sạc 2 giờ#Cổng sạc: LightningSạc không dây#Tương thích: AndroidiOS (iPhone)iPadOS (iPad)MacOS (Macbook, iMac)#Tiện ích: Chống nước IPX4Có mic thoạiSạc không dây#Hỗ trợ kết nối: Bluetooth 5.0#Điều khiển bằng: Cảm ứng chạm Hãng Apple',
                'quantity' => '0',
                'sale' => '15',
                'star' => '3',
                'feature' => '1',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '4',
                'product_name' => ' Tai nghe chụp tai Bluetooth AirPods Max Apple MGYH3',
                'price' => '8100000',
                'image' => 'bluetooth-airpods-max-apple-thumb-600x600.jpg',
                'description' => 'Pin: Dùng 20 giờ - Sạc 3 giờ#Cổng sạc: Lightning#Công nghệ âm thanh: Active Noise CancellationAdaptive EQChip Apple H1Spatial AudioTransparency Mode#Tương thích: AndroidiOS (iPhone)#Tiện ích: Chống ồn Sạc nhanh#Hỗ trợ kết nối: Bluetooth 5.0#Điều khiển bằng: Phím nhấn Hãng Apple',
                'quantity' => '10',
                'feature' => '1',
                'sale' => '15',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '4',
                'product_name' => 'Tai nghe nhét trong EarPods Lightning Apple MMTN2',
                'price' => '632000',
                'image' => 'tai-nghe-earpods-cong-lightning-apple-mmtn2-avatar-1-600x600.jpg',
                'description' => 'Jack cắm: Lightning#Tương thích: iOS (iPhone)#Tiện ích: Có mic thoại#Điều khiển bằng: Phím nhấn#Phím điều khiển: Chuyển bài hátMic thoạiNghe/nhận cuộc gọiPhát/dừng chơi nhạcTăng/giảm âm lượng Hãng Apple',
                'quantity' => '10',
                'feature' => '1',
                'sale' => '10',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '2',
                'product_name' => 'Samsung Galaxy S22 Ultra',
                'price' => '30990000',
                'image' => 'samsung-galaxys22ultra.jpg',
                'description' => 'Màn hình: Dynamic AMOLED 2X6.8"Quad HD+ (2K+)#Hệ điều hành: Android 12#Camera sau: Chính 108 MP & Phụ 12 MP, 10 MP, 10 MP#Camera trước: 40 MP#Chip: Snapdragon 8 Gen 1 8 nhân#RAM: 8 GB#Bộ nhớ trong: 128 GB#SIM: 2 Nano SIM hoặc 1 Nano SIM + 1 eSIM Hỗ trợ 5G#Pin, Sạc: 5000 mAh, 45 W',
                'quantity' => '5',
                'feature' => '1',
                'sale' => '0',
                'star' => '5',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '2',
                'product_name' => 'Samsung Galaxy S21 Ultra',
                'price' => '25990000',
                'image' => 'samsung-galaxys21ultra.jpg',
                'description' => 'Màn hình: Dynamic AMOLED 2X6.8"Quad HD+ (2K+)#Hệ điều hành: Android 11#Camera sau: Chính 108 MP & Phụ 12 MP, 10 MP, 10 MP#Camera trước: 40 MP#Chip: Exynos 2100#RAM: 12 GB#Bộ nhớ trong: 128 GB#SIM: 2 Nano SIM hoặc 1 Nano SIM + 1 eSIM Hỗ trợ 5G#Pin, Sạc: 5000 mAh, 25 W',
                'quantity' => '10',
                'feature' => '1',
                'sale' => '5',
                'star' => '4',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '2',
                'product_name' => 'Samsung Galaxy Z Flip3',
                'price' => '19990000',
                'image' => 'samsung-galaxyzflip3.jpg',
                'description' => 'Màn hình: Dynamic AMOLED 2X6.8"Quad HD+ (2K+)#Hệ điều hành: Android 11#Camera sau: 2 camera 12 MP#Camera trước: 10 MP#Chip: Snapdragon 888#RAM: 8 GB#Bộ nhớ trong: 128 GB#SIM: 1 Nano SIM & 1 eSIM Hỗ trợ 5G#Pin, Sạc: 3300 mAh, 15 W',
                'quantity' => '10',
                'feature' => '1',
                'sale' => '5',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '2',
                'product_name' => 'Samsung Galaxy Z Fold3',
                'price' => '36990000',
                'image' => 'samsung-galaxyzfold3.jpg',
                'description' => 'Màn hình: Dynamic AMOLED 2XChính 7.6" & Phụ 6.2"Full HD+#Hệ điều hành: Android 11#Camera sau: 3 camera 12 MP#Camera trước: 10 MP & 4 MP#Chip: Snapdragon 888#RAM: 12 GB#Bộ nhớ trong: 256 GB#SIM: 2 Nano SIM + 1 eSIM Hỗ trợ 5G#Pin, Sạc: 4400 mAh, 25 W',
                'quantity' => '5',
                'feature' => '1',
                'sale' => '10',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '2',
                'product_name' => 'Samsung Galaxy S22+',
                'price' => '25990000',
                'image' => 'samsung-galaxys22plus.jpg',
                'description' => 'Màn hình: Dynamic AMOLED 2X6.6"Full HD+#Hệ điều hành: Android 12#Camera sau: Chính 50 MP & Phụ 12 MP, 10 MP#Camera trước: 10 MP#Chip: Snapdragon 8 Gen 1 8 nhân#RAM: 8 GB#Bộ nhớ trong: 128 GB#SIM: 2 Nano SIM hoặc 1 Nano SIM + 1 eSIM Hỗ trợ 5G#Pin, Sạc: 4500 mAh,45 W',
                'quantity' => '15',
                'feature' => '1',
                'sale' => '15',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '2',
                'product_name' => 'Samsung Galaxy A32',
                'price' => '6490000',
                'image' => 'samsung-galaxy-a32-4g-thumb-tim-600x600-600x600.jpg',
                'description' => 'Màn hình 6.4: Chip MediaTek Helio G80 RAM 6 GB, ROM 128 GB#Camera sau: Chính 64 MP & Phụ 8 MP, 5MP, 5MP#Camera trước: 20 MP Pin 5000 mAh, Sạc 15 W',
                'quantity' => '15',
                'feature' => '1',
                'sale' => '15',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '2',
                'product_name' => 'Samsung Galaxy M51',
                'price' => '6290000',
                'image' => 'samsung-galaxy-m51-trang-new-600x600-600x600.jpg',
                'description' => 'Màn hình 6.7: Chip Snapdragon 730 RAM 8 GB, ROM 128 GB#Camera sau: Chính 64 MP & Phụ 12 MP, 5 MP, 5 MP#Camera trước: 32 MP Pin 7000 mAh, Sạc 25 W',
                'quantity' => '15',
                'feature' => '1',
                'sale' => '15',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '2',
                'product_name' => 'Samsung Galaxy A22',
                'price' => '5890000',
                'image' => 'samsung-galaxy-a22-4g-mint-1-600x600.jpg',
                'description' => 'Màn hình 6.4: Chip MediaTek MT6769V RAM 6 GB, ROM 128 GB#Camera sau: Chính 48 MP & Phụ 8 MP, 2 MP, 2 MP#Camera trước: 13 MP Pin 5000 mAh, Sạc 15 W ',
                'quantity' => '15',
                'feature' => '1',
                'sale' => '15',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '2',
                'product_name' => 'Samsung Galaxy A23',
                'price' => '5690000',
                'image' => 'samsung-galaxy-a23-cam-thumb-600x600.jpg',
                'description' => 'Màn hình 6.6: Chip Snapdragon 680 8 nhân RAM 4 GB, ROM 128 GB#Camera sau: Chính 50 MP & Phụ 5 MP, 2 MP, 2 MP#Camera trước: 8 MP Pin 5000 mAh, Sạc 25 W',
                'quantity' => '15',
                'feature' => '1',
                'sale' => '15',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            //Tai nghe
            [
                'manu_id' => '2',
                'product_name' => 'Tai nghe Bluetooth True Wireless Galaxy Buds Pro Bạc',
                'price' => '4990000',
                'image' => 'bluetooth-true-wireless-galaxy-buds-pro-bac-thumb-600x600.jpg',
                'description' => 'Thời gian tai nghe: Dùng 8 giờ - Sạc 3 giờ#Thời gian hộp sạc: Dùng 20 giờ - Sạc 3 giờ#Cổng sạc: Sạc không dâyType-C#Công nghệ âm thanh: Active Noise CancellationDolby Head Tracking#Tương thích: AndroidiOS (iPhone)Windows#Ứng dụng kết nối: SmartThings#Tiện ích: Chống nước IPX7Chống ồnCó mic thoại#Hỗ trợ kết nối: Bluetooth 5.0#Điều khiển bằng: Cảm ứng chạm Hãng Samsung',
                'quantity' => '10',
                'feature' => '1',
                'sale' => '15',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '2',
                'product_name' => 'Tai nghe Bluetooth True Wireless Samsung Galaxy Buds Live R180 Gold',
                'price' => '1990000',
                'image' => 'ai-nghe-bluetooth-true-wireless-samsung-galaxy-buds-live-r180-gold-thumb-600x600.jpg',
                'description' => 'Thời gian tai nghe: Dùng 6 giờ - Sạc 1 giờ#Thời gian hộp sạc: Dùng 21 giờ - Sạc 1 giờ#Cổng sạc: Sạc không dâyType-C#Công nghệ âm thanh: Active Noise Cancellation#Tương thích: Android, iOS, Windows#Ứng dụng kết nối: Galaxy Wearable#Tiện ích: Chống nước IPX2Có mic thoạiSử dụng độc lập 1 bên tai nghe#Hỗ trợ kết nối: Bluetooth 5.0#Điều khiển bằng: Cảm ứng chạm Hãng Samsung',
                'quantity' => '5',
                'feature' => '1',
                'sale' => '15',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '2',
                'product_name' => 'Tai nghe Bluetooth True Wireless Samsung Galaxy Buds 2 R177N Trắng',
                'price' => '2990000',
                'image' => 'samsung-galaxy-buds-2-r177n-trang-thumb-3-600x600.jpg',
                'description' => 'Thời gian tai nghe: Dùng 7.5 giờ - Sạc 1.5 giờ#Thời gian hộp sạc: Dùng 29 giờ - Sạc 1.5 giờ#Cổng sạc: Sạc không dâyType-C#Công nghệ âm thanh: Active Noise CancellationAmbient Sound#Tương thích: AndroidRam 1.5G trở lên#Ứng dụng kết nối: Galaxy Wearable#Tiện ích: Chống nước IPX2Có mic thoại#Hỗ trợ kết nối: Bluetooth 5.2#Điều khiển bằng: Cảm ứng chạm Hãng Samsung',
                'quantity' => '10',
                'feature' => '1',
                'sale' => '15',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '2',
                'product_name' => 'Tai nghe Bluetooth True Wireless Samsung Galaxy Buds 2 R177N',
                'price' => '2990000',
                'image' => 'samsung-galaxy-buds-2-r177n-600x600.jpg',
                'description' => 'Thời gian tai nghe: Dùng 7.5 giờ - Sạc 1.5 giờ#Thời gian hộp sạc: Dùng 29 giờ - Sạc 1.5 giờ#Cổng sạc: Sạc không dâyType-C#Công nghệ âm thanh: Active Noise CancellingAmbient Sound#Tương thích: AndroidRam 1.5G trở lên#Ứng dụng kết nối: Galaxy Wearable#Tiện ích: Chống nước IPX2Có mic thoại#Hỗ trợ kết nối: Bluetooth 5.2#Điều khiển bằng: Cảm ứng chạm Hãng Samsung',
                'quantity' => '10',
                'feature' => '1',
                'sale' => '15',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '2',
                'product_name' => 'Tai nghe nhét tai Samsung IA500 Đen',
                'price' => '300000',
                'image' => 'nhet-tai-samsung-ia500-den-041221-063201-600x600.jpg',
                'description' => 'Jack cắm: 3.5 mm#Tương thích: AndroidiOS (iPhone)MacOS#Tiện ích: Có mic thoạiĐệm tai đi kèm#Điều khiển bằng: Phím nhấn#Phím điều khiển: Phát/dừng chơi nhạcTăng/giảm âm lượng Hãng Samsung',
                'quantity' => '6',
                'feature' => '1',
                'sale' => '15',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '3',
                'product_name' => 'OPPO Reno7 Z',
                'price' => '10490000',
                'image' => 'oppo-reno7.jpg',
                'description' => 'Màn hình: AMOLED6.43"Full HD+#Hệ điều hành: Android 11#Camera sau: Chính 64 MP & Phụ 2 MP, 2 MP#Camera trước: 16 MP#Chip: Snapdragon 695 5G 8 nhân#RAM: 8 GB#Bộ nhớ trong: 128 GB#SIM: 2 Nano SIM (SIM 2 chung khe thẻ nhớ) Hỗ trợ 5G#Pin, Sạc: 4500 mAh, 33 W',
                'quantity' => '15',
                'feature' => '1',
                'sale' => '0',
                'star' => '5',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '3',
                'product_name' => 'OPPO Reno6',
                'price' => '11990000',
                'image' => 'oppo-reno6.jpg',
                'description' => 'Màn hình: AMOLED6.43"Full HD+#Hệ điều hành: Android 11#Camera sau: Chính 64 MP & Phụ 8 MP, 2 MP#Camera trước: 32 MP#Chip: MediaTek Dimensity 900 5G#RAM: 8 GB#Bộ nhớ trong: 128 GB#SIM: 2 Nano SIM Hỗ trợ 5G#Pin, Sạc: 4300 mAh, 65 W',
                'quantity' => '5',
                'feature' => '1',
                'sale' => '5',
                'star' => '4',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '3',
                'product_name' => 'OPPO Reno5',
                'price' => '8990000',
                'image' => 'oppo-reno5.jpg',
                'description' => 'Màn hình: AMOLED6.43"Full HD+#Hệ điều hành: Android 11#Camera sau: Chính 64 MP & Phụ 8 MP, 2 MP, 2 MP#Camera trước: 32 MP#Chip: Snapdragon 765G#RAM: 8 GB#Bộ nhớ trong: 128 GB#SIM: 2 Nano SIM Hỗ trợ 5G#Pin, Sạc: 4300 mAh, 65 W',
                'quantity' => '5',
                'feature' => '1',
                'sale' => '5',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '3',
                'product_name' => 'OPPO A16',
                'price' => '3990000',
                'image' => 'oppo-a16.jpg',
                'description' => 'Màn hình: IPS LCD 6.52" HD+#Hệ điều hành: Android 11#Camera sau: Chính 13 MP & Phụ 2 MP, 2 MP#Camera trước: 8 MP#Chip: MediaTek Helio G35#RAM: 3 GB#Bộ nhớ trong: 32 GB#SIM: 2 Nano SIM Hỗ trợ 4G#Pin, Sạc: 5000 mAh, 10 W',
                'quantity' => '5',
                'feature' => '0',
                'sale' => '10',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '3',
                'product_name' => 'OPPO A15s',
                'price' => '4290000',
                'image' => 'oppo-a15s.jpg',
                'description' => 'Màn hình: IPS LCD 6.52" HD+#Hệ điều hành: Android 11#Camera sau: Chính 13 MP & Phụ 2 MP, 2 MP#Camera trước: 8 MP#Chip: MediaTek Helio P35#RAM: 4 GB#Bộ nhớ trong: 64 GB#SIM: 2 Nano SIM Hỗ trợ 4G#Pin, Sạc: 4230 mAh, 10 W',
                'quantity' => '10',
                'feature' => '0',
                'sale' => '15',
                'star' => '3',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '3',
                'product_name' => 'OPPO A95',
                'price' => '6990000',
                'image' => 'oppo-a95-4g-bac-2-600x600.jpg',
                'description' => 'Màn hình 6.43: Chip Snapdragon 662 RAM 8 GB, ROM 128 GB#Camera sau: Chính 48 MP & Phụ 2 MP, 2 MP#Camera trước: 16 MP Pin 5000 mAh, Sạc 33 W',
                'quantity' => '15',
                'feature' => '1',
                'sale' => '0',
                'star' => '5',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '3',
                'product_name' => 'OPPO A76',
                'price' => '5990000',
                'image' => 'OPPO-A76-đen-600x600.jpg',
                'description' => 'Màn hình 6.56: Chip Snapdragon 680 8 nhân RAM 6 GB, ROM 128 GB#Camera sau: Chính 13 MP & Phụ 2 MP#Camera trước: 8 MP Pin 5000 mAh, Sạc 33 W',
                'quantity' => '10',
                'feature' => '1',
                'sale' => '0',
                'star' => '5',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '3',
                'product_name' => 'OPPO A74 5G',
                'price' => '5700000',
                'image' => 'oppo-a74-5g-silver-01-600x600.jpg',
                'description' => 'Màn hình 6.5: Chip Snapdragon 480 8 nhân 5G RAM 6 GB, ROM 128 GB#Camera sau: Chính 48 MP & Phụ 8 MP, 2 MP, 2 MP#Camera trước: 16 MP Pin 5000 mAh, Sạc 18 W',
                'quantity' => '5',
                'feature' => '1',
                'sale' => '0',
                'star' => '5',
                'created_at' => '2022-05-26',
            ],
            [
                'manu_id' => '3',
                'product_name' => 'OPPO A15s',
                'price' => '4190000',
                'image' => 'oppo-a15s-xanh-600x600-3-600x600.jpg',
                'description' => 'Màn hình 6.52: Chip MediaTek Helio P35 RAM 4 GB, ROM 64 GB#Camera sau: Chính 13 MP & Phụ 2 MP, 2 MP#Camera trước: 8 MP Pin 4230 mAh, Sạc 10 W',
                'quantity' => '15',
                'feature' => '1',
                'sale' => '0',
                'star' => '5',
                'created_at' => '2022-05-26',
            ]
        ]);
    }
}